language: python

python:
- "3.7.4"

install: pip install -r requirements.txt

before script:
- python manage.py collectstatic --noinput

script:
- flake8 .
- black --check
-coverage run --source=polls,swe1app manage.py test